## Listas

### 1.1 Criação de listas


In [9]:
lista1 = [1, 2, 3, 4]
lista2 = list(range(1, 5))

lista3 = ['Ricardo', 1, 3.14, [1, 2, 3], {'nome': 'Ricardo'}, (1,2,3,4)]

lista3

['Ricardo', 1, 3.14, [1, 2, 3], {'nome': 'Ricardo'}, (1, 2, 3, 4)]

In [16]:
# Toda posição em Python se inicia em ZERO
lista3[3]

2

### 1.2. Acessando elementos

In [ ]:
primeiro_elemento = lista1[0]
ultimo_elemento = lista1[-1]

#slicing (primeiro ao terceiro elemento)
lista3[0:3]

### 1.3. Manipulação de listas



In [19]:
lista3

['Ricardo', 1, 3.14, [1, 2, 3], {'nome': 'Ricardo'}, (1, 2, 3, 4), 'Eduardo']

In [23]:
lista1
#lista3.append('Eduardo') #Adicionar elementos (append, extend, insert)

#lista3.remove(3.14) #Remover elementos (remove, pop, del)
#lista1.reverse() #Ordenar e inverter listas (sort, reverse)
#lista2.reverse() #Ordenar e inverter listas (sort, reverse)
lista1

[4, 3, 2, 1]

In [27]:
lista1

['Ricardo', 7, 5, 4, 3, 1, 'Ricardo']

In [24]:
lista4 = []
for elemento in range(15):
    if elemento > 5:
        print(elemento)
        lista4.append(elemento)

lista4

6
7
8
9
10
11
12
13
14


[6, 7, 8, 9, 10, 11, 12, 13, 14]

In [31]:
lista6 = ['Ricardo', 'Anderson', 'João']
lista6.sort()

In [32]:
lista6

['Anderson', 'João', 'Ricardo']

## Tuplas

## 2.1. Criação de tuplas

In [25]:
tupla1 = (1, 2, 3, 4)
tupla2 = tuple(range(1, 5))

### 2.2. Acessando elementos

In [26]:
primeiro_elemento = tupla1[0]
ultimo_elemento = tupla1[-1]

In [30]:
for elemento in range(3):
    if elemento < 2:
        valor = input('Digite ID do aluno: ')
        tupla = (valor, )

valor1 = input('Digite ID do aluno: ')
valor2 = input('Digite ID do aluno: ')
valor3 = input('Digite ID do aluno: ')

tupla = (valor1, valor2, valor3)

In [31]:
tupla

('10', '15', '20')

### 2.3. Imutabilidade das tuplas


In [29]:
# Não é possível modificar elementos de uma tupla
# A linha abaixo causará um erro

tupla1[0] = 4

TypeError: 'tuple' object does not support item assignment

## Dicionários

### Conceito de Dicionários

1. **Definição**: Um dicionário em Python é uma coleção desordenada de itens. Enquanto outras estruturas de dados, como listas ou tuplas, são indexadas por um intervalo de números, os dicionários são indexados por chaves, que podem ser de qualquer tipo imutável, como strings ou números.

2. **Características**:
   - Cada par chave-valor é separado por vírgulas.
   - Os dicionários são delimitados por chaves `{}`.
   - As chaves são únicas dentro de um dicionário.

3. **Utilidade**: Dicionários são ideais para armazenar dados que podem ser identificados por uma chave única, como detalhes de um contato em uma agenda telefônica (nome, número, endereço, etc).

### Criando e Usando Dicionários

#### Estrutura Básica de um Dicionário

```python
meu_dicionario = {
    'chave1': 'valor1',
    'chave2': 'valor2',
    'chave3': 'valor3'
}
```

- Cada item tem uma chave e um valor correspondente, expresso como `chave: valor`.

#### Exemplo Prático

Vamos criar um dicionário para armazenar informações de um livro:

```python
livro = {
    'titulo': '1984',
    'autor': 'George Orwell',
    'ano': 1949
}

# Acessando elementos
print(livro['titulo'])  # Saída: 1984

# Adicionando um novo par chave-valor
livro['isbn'] = '1234567890'

# Atualizando um valor existente
livro['ano'] = 1948

# Removendo um par chave-valor
del livro['isbn']
```

### Métodos Comuns de Dicionários

- **`get()`**: Retorna o valor da chave especificada. Se a chave não existir, retorna `None` (ou um valor padrão definido).

  ```python
  print(livro.get('autor', 'Autor desconhecido'))
  ```

- **`keys()`**: Retorna uma nova visualização das chaves no dicionário.

  ```python
  print(list(livro.keys()))  # Saída: ['titulo', 'autor', 'ano']
  ```

- **`values()`**: Retorna uma nova visualização dos valores no dicionário.

  ```python
  print(list(livro.values()))  # Saída: ['1984', 'George Orwell', 1948]
  ```

- **`items()`**: Retorna uma nova visualização dos pares chave-valor no dicionário.

  ```python
  for chave, valor in livro.items():
      print(f"{chave}: {valor}")
  ```

- **`pop()`**: Remove o item com a chave especificada e retorna o seu valor.

  ```python
  ano = livro.pop('ano')
  ```

### Boas Práticas

1. **Chaves Significativas**: Use chaves que sejam significativas e descrevam bem o valor associado.
2. **Evitar Chaves Duplicadas**: As chaves duplicadas serão sobrescritas.
3. **Uso de `get()`**: Prefira usar `get()` para acessar elementos para evitar erros se a chave não existir.

### Conclusão

Os dicionários são uma ferramenta incrivelmente útil e poderosa em Python, proporcionando uma maneira eficiente de armazenar e manipular dados de forma estruturada. Eles são especialmente úteis quando você precisa de uma associação lógica entre pares chave-valor.

### Olhando na prática

In [42]:
dicionario1 = {
   'Alunos': ['Davidson', 'Maria', 'Leonan'],
   'Professores': ['Ricardo', 'Eder', 'Alisson'], 
   'Idade': [25, 22, 20], 
   'Endereco': ['Rua...', 'Rua...', 'Rua...'],
   'Exemplo': 12,
   'Exemplo1': 3.14
}

dicionario2 = dict(um=1, dois=2, três=3)

In [43]:
# Adicionando valor em uma chave especifica
dicionario1['Alunos'].append('Roberta')
dicionario1['Alunos']

['Davidson', 'Maria', 'Leonan', 'Roberta']

In [44]:
dicionario1.values()

dict_values([['Davidson', 'Maria', 'Leonan', 'Roberta'], ['Ricardo', 'Eder', 'Alisson'], [25, 22, 20], ['Rua...', 'Rua...', 'Rua...'], 12, 3.14])

In [45]:
dicionario1.keys()

dict_keys(['Alunos', 'Professores', 'Idade', 'Endereco', 'Exemplo', 'Exemplo1'])

In [46]:
# Metódo items (retorna uma tupla onde tupla[0] é a chave e tupla[1] é o valor daquela chave)
dicionario1.items()

dict_items([('Alunos', ['Davidson', 'Maria', 'Leonan', 'Roberta']), ('Professores', ['Ricardo', 'Eder', 'Alisson']), ('Idade', [25, 22, 20]), ('Endereco', ['Rua...', 'Rua...', 'Rua...']), ('Exemplo', 12), ('Exemplo1', 3.14)])

In [47]:
dicionario1.get('Alunos', 'Professores')

['Davidson', 'Maria', 'Leonan', 'Roberta']

In [48]:
dicionario1.get('Professores')

['Ricardo', 'Eder', 'Alisson']

In [50]:
# Iterando sobre nossos dados do dicionario
for chave, valor in dicionario1.items():
    if chave=='Alunos':
        print(valor)


['Davidson', 'Maria', 'Leonan', 'Roberta']


In [51]:
dicionario1['Curso'] = ['Python', 'Java', 'Golang', 'C#', 'C++'] #Adicionar elementos (atribuição direta)

dicionario1.pop('Curso') #Remover chave com elementos (pop, del)

#Iterar pelos elementos (keys, values, items)
for chave, valor in dicionario1.items():
    print(chave, valor)

Alunos ['Davidson', 'Maria', 'Leonan', 'Roberta']
Professores ['Ricardo', 'Eder', 'Alisson']
Idade [25, 22, 20]
Endereco ['Rua...', 'Rua...', 'Rua...']
Exemplo 12
Exemplo1 3.14


In [53]:
# Exemplo de 'aninhamento'
dict_exemplo = {'exemplo': 'dicionario',
                'criando_dict': {'outro_dict': ['aninhado']}}

In [65]:
dict_exemplo['criando_dict']['outro_dict'].sort()

In [66]:
dict_exemplo['criando_dict']['outro_dict']

['Test', 'Test', 'Teste']

## Diferenças entre os tipos de Dados Complexos

- Listas: sequências ordenadas, mutáveis e podem conter elementos duplicados.

- Tuplas: sequências ordenadas, imutáveis e podem conter elementos duplicados.

- Dicionários: coleções não ordenadas de pares chave-valor, mutáveis e chaves únicas.

## Numpy

Numpy é uma biblioteca para a linguagem de programação Python que suporta grandes matrizes e matrizes multidimensionais, além de uma grande coleção de funções matemáticas para operar nessas matrizes. 

In [67]:
import numpy as np

# Matriz de zeros: Uma matriz cheia de zeros.
zeros = np.zeros((3, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [70]:
zeros[1][1]

0.0

In [71]:
# Matriz de uns: Uma matriz cheia de uns.
ones = np.ones((3, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [72]:
# Matriz identidade: Uma matriz quadrada onde todos os elementos da diagonal são 1 e os outros são 0.
identity = np.eye(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
identity[2][1]

0.0

In [75]:
# Matriz aleatoria

random_matrix = np.random.rand(3, 3)
random_matrix

array([[0.97543728, 0.76671034, 0.8827521 ],
       [0.23379469, 0.00711259, 0.95992678],
       [0.74103283, 0.59374568, 0.8574814 ]])

### Operacoes

In [76]:
# Adicao de Matrizes

A = np.array([[1, 2], [3, 4]])
# 1 2
# 3 4

B = np.array([[5, 6], [7, 8]])
# 5 6
# 7 8

C = A + B
C

array([[ 6,  8],
       [10, 12]])

In [77]:
# Multiplicacao de Matrizes
D = np.dot(A, B)
D

array([[19, 22],
       [43, 50]])

In [78]:
# Transposta de uma Matriz
E = A.T
E

array([[1, 3],
       [2, 4]])

#### Outras aplicacoes

##### Aplicações de Matrizes com Numpy

**Processamento de Imagens:** Matrizes podem ser usadas para representar imagens e aplicar filtros, rotações etc.

**Sistemas de Equações Lineares:** Resolver um sistema de equações lineares pode ser feito através da manipulação de matrizes

```python
coeficientes = np.array([[2, 1], [1, 1]])

constantes = np.array([4, 2])

solucao = np.linalg.solve(coeficientes, constantes)

```

**Análise de Dados:** Em ciência de dados, você pode usar matrizes para guardar datasets e fazer operações como médias, somas, etc, de forma mais eficiente.

**Aprendizado de Máquina:** Bibliotecas como TensorFlow e PyTorch usam Numpy ou estruturas semelhantes para efetuar operações de aprendizado de máquina como backpropagation em redes neurais.

**Simulações Físicas:** Em física computacional, matrizes são usadas para simular sistemas e resolver equações diferenciais parciais.

## Conceito de Funções

1. **Definição**: Uma função é um bloco de código que só é executado quando é chamado. Você pode passar dados, conhecidos como parâmetros, para uma função. Uma função pode retornar dados como resultado.

2. **Reutilização de Código**: Em vez de escrever o mesmo código várias vezes para diferentes entradas, você pode escrever uma função que pode ser reutilizada várias vezes com diferentes parâmetros.

3. **Organização**: As funções ajudam a tornar o seu código mais organizado e mais fácil de seguir.

## Criando e Usando Funções em Python

### Estrutura Básica de uma Função

```python
def nome_da_funcao(parametro1, parametro2):
    # Bloco de código
    return resultado
```

- `def`: Palavra-chave para definir uma função.
- `nome_da_funcao`: Nome único para identificar a função.
- `parametro1, parametro2`: Argumentos ou parâmetros que a função pode receber.
- `return`: Retorna um valor como resultado da função (opcional).

### Exemplo Prático

Vamos criar uma função simples chamada `soma`, que adiciona dois números:

```python
def soma(a, b):
    return a + b

# Usando a função
resultado = soma(5, 3)
print(resultado)  # Saída: 8
```

Neste exemplo, `soma` é uma função que pega dois parâmetros `a` e `b`, e retorna a soma deles.

## Parâmetros Avançados

- **Parâmetros Padrão**: Você pode definir um valor padrão para um parâmetro. Se o argumento não for fornecido, este valor padrão será usado.

  ```python
  def saudacao(nome="Visitante"):
      return "Olá, " + nome

  print(saudacao("Ana"))  # Saída: Olá, Ana
  print(saudacao())       # Saída: Olá, Visitante
  ```

- **Argumentos de Palavra-chave**: Permite que você especifique argumentos pelo nome, tornando seu código mais legível.

  ```python
  def informacao(nome, idade):
      return f"Nome: {nome}, Idade: {idade}"

  print(informacao(idade=30, nome="Carlos"))  # Saída: Nome: Carlos, Idade: 30
  ```

- **Número Variável de Argumentos**: Às vezes, você pode querer uma função que aceite um número variável de argumentos.

  ```python
  def soma(*numeros):
      return sum(numeros)

  print(soma(1, 2, 3, 4))  # Saída: 10
  ```

## Boas Práticas

1. **Nome Significativo**: O nome da função deve refletir o que ela faz.
2. **Funções Pequenas e Focadas**: Cada função deve fazer apenas uma coisa bem.
3. **Documentação**: Comentar ou documentar o que a função faz.

## Conclusão

As funções são ferramentas poderosas em Python que ajudam a tornar o código mais modular, reutilizável e claro. Ao compreender como definir e usar funções, você pode escrever programas mais eficientes e organizados.

In [ ]:
def soma(a: int, b: int) -> int:
    '''
    Funcao criada para somar 2 parametros
    
    Args:
    a (int): primeiro elemento da minha soma
    b (int): segundo elemento da minha soma
    
    Return:
    c (int): resultado da minha soma
    '''

## Exercicios

Dada uma lista, retorne uma nova lista que contém apenas elementos únicos da lista original.

In [90]:
def elementos_unicos(lista):
    
    unicos = []
    for elemento in lista:
        if elemento not in unicos:
            print(f'Unico {elemento}')
            unicos.append(elemento)
    
    return unicos

# Testando a função
lista_original = [1, 2, 2, 3, 4, 3, 5]
print(elementos_unicos(lista_original))  # Deve imprimir [1, 2, 3, 4, 5]

Unico 1
Unico 2
Unico 3
Unico 4
Unico 5
[1, 2, 3, 4, 5]


Dado um texto, crie um dicionário onde as chaves são palavras e os valores são o número de vezes que cada palavra aparece no texto.

In [ ]:
def contagem_palavras(texto):
    palavras = texto.split()  # Separa o texto em uma lista de palavras
    contagem = {}  # Inicializa um dicionário vazio para armazenar a contagem das palavras
    
    for palavra in palavras:
        palavra = palavra.lower()  # Converte a palavra para minúsculas para que a contagem seja insensível a maiúsculas e minúsculas
        if palavra in contagem:
            contagem[palavra] += 1  # Incrementa a contagem se a palavra já existe no dicionário
        else:
            contagem[palavra] = 1  # Adiciona a palavra ao dicionário com contagem 1 se ela ainda não existe
    
    return contagem

# Testando a função
texto = "Este é um texto. Este texto é um exemplo."
print(contagem_palavras(texto))

In [5]:
## Crie uma função que retorne se a pessoa esta normal, abaixo do peso, sobrepeso ou obesa baseada
# em seu IMC

def calcula_imc():
    peso = float(input('Digite seu Peso: '))
    altura = float(input('Digite sua Altura em Metros: '))
     
    imc = peso / (altura ** 2)
    if imc < 18.5:
        return "Abaixo do peso"
    elif 18.5 <= imc < 25: # (imc >= 18.5) & (imc < 25)
        return "Normal"
    elif 25 <= imc < 30:
        return "Sobrepeso"
    else:
        return "Obesidade"

imc_ricardo = calcula_imc()

### O que são APIs?

1. **Definição**: Uma API é um conjunto de regras e definições que permite que diferentes softwares se comuniquem. Ela define os métodos e dados que você pode solicitar de outros serviços ou aplicativos, e como fazer essas solicitações.

2. **Analogia**: Pense em uma API como um garçom em um restaurante. Você (o cliente) faz um pedido (uma solicitação) através do garçom (API) para a cozinha (o sistema/software). A cozinha prepara o pedido e o garçom entrega o resultado de volta para você.

3. **Utilidade**: APIs são usadas para conectar serviços e transferir dados entre diferentes sistemas de forma programática. Por exemplo, uma API de previsão do tempo pode fornecer dados meteorológicos a outros aplicativos.

### Tipos de APIs

1. **APIs Web / RESTful**: Usadas para comunicação na internet. Utilizam protocolos HTTP/HTTPS para enviar e receber solicitações e respostas, geralmente no formato JSON ou XML.

2. **APIs de Bibliotecas/Frameworks**: Fornecem conjuntos de funções e métodos que permitem a interação com outro software ou sistema operacional. Exemplo: APIs do jQuery ou do React.

3. **APIs de Sistema Operacional**: Permitem que aplicativos interajam com o sistema operacional. Por exemplo, a API do Windows.

### Como Funcionam as APIs?

#### Estrutura de Uma Solicitação API

1. **Endpoint**: O URL para onde você envia a solicitação. Exemplo: `https://api.exemplo.com/dados`

2. **Método**: O tipo de operação que você deseja realizar. Os mais comuns são:
   - `GET`: Solicitar dados.
   - `POST`: Enviar dados para serem processados.
   - `PUT`: Atualizar dados.
   - `DELETE`: Excluir dados.

3. **Cabeçalhos**: Contêm informações adicionais (como tipo de conteúdo, autenticação) necessárias para processar a solicitação.

4. **Corpo da Solicitação (Payload)**: Dados enviados em uma solicitação `POST` ou `PUT`.

5. **Parâmetros**: Usados para fornecer informações adicionais na solicitação. Exemplo: `https://api.exemplo.com/dados?userid=123`

#### Resposta da API

- **Código de Status**: Indica se a solicitação foi bem-sucedida (ex: 200 OK, 404 Not Found).
- **Corpo da Resposta**: Contém os dados ou resultados da solicitação, geralmente em formato JSON ou XML.

### Boas Práticas no Uso de APIs

1. **Leia a Documentação**: Entenda os limites, os requisitos de autenticação e os formatos de dados esperados.
2. **Manuseie Erros**: Implemente tratamento de erros para lidar com falhas de solicitação ou respostas inesperadas.
3. **Segurança**: Use autenticação e criptografia (HTTPS) para proteger as informações transmitidas.
4. **Respeite os Limites de Taxa**: Muitas APIs têm limitações de quantas solicitações você pode fazer em um determinado período.

### Conclusão

APIs são essenciais para a integração e comunicação entre diferentes sistemas e serviços. Elas permitem que aplicativos e softwares compartilhem dados e funcionalidades de maneira segura e eficiente, abrindo um mundo de possibilidades para novas funcionalidades e automação.

### Utilizando uma API

In [79]:
!pip install requests

You should consider upgrading via the '/home/ricardo/.pyenv/versions/3.8.12/bin/python3.8 -m pip install --upgrade pip' command.


In [80]:
import requests

# Nome da moeda que desejamos obter informações
coin = "bitcoin"

# URL da API CoinGecko
url = f"https://api.coingecko.com/api/v3/coins/{coin}"

# Fazendo a solicitação para a API
response = requests.get(url)

In [81]:
response

<Response [200]>

In [82]:
# Verificando se a solicitação foi bem sucedida
if response.status_code == 200:
    # Convertendo a resposta da API para um dicionário
    data = response.json()
else:
    print("Ocorreu um erro ao obter os dados da API.")

In [91]:
data['market_data']['current_price']

{'aed': 132070,
 'ars': 12799788,
 'aud': 54833,
 'bch': 165.322,
 'bdt': 3980383,
 'bhd': 13550.22,
 'bmd': 35959,
 'bnb': 157.75,
 'brl': 176220,
 'btc': 1.0,
 'cad': 49260,
 'chf': 31763,
 'clp': 31268533,
 'cny': 255196,
 'czk': 807790,
 'dkk': 245533,
 'dot': 7334,
 'eos': 55143,
 'eth': 18.496192,
 'eur': 32935,
 'gbp': 28665,
 'hkd': 280322,
 'huf': 12536285,
 'idr': 557935274,
 'ils': 133603,
 'inr': 2997020,
 'jpy': 5327282,
 'krw': 46608375,
 'kwd': 11078.98,
 'lkr': 11810388,
 'ltc': 540.108,
 'mmk': 75475443,
 'mxn': 618561,
 'myr': 167316,
 'ngn': 29438380,
 'nok': 383629,
 'nzd': 59407,
 'php': 1992658,
 'pkr': 10266855,
 'pln': 144039,
 'rub': 3173770,
 'sar': 134866,
 'sek': 375961,
 'sgd': 48105,
 'thb': 1265211,
 'try': 1035648,
 'twd': 1128643,
 'uah': 1297885,
 'usd': 35959,
 'vef': 3600.56,
 'vnd': 868046294,
 'xag': 1511.81,
 'xau': 17.99,
 'xdr': 26997,
 'xlm': 314537,
 'xrp': 61811,
 'yfi': 4.712532,
 'zar': 669416,
 'bits': 999741,
 'link': 2644,
 'sats': 99974

### Como fazer chamada na API do Kaggle?

In [92]:
import subprocess
import sys
import os
import json

def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])

install('kaggle')

You should consider upgrading via the '/home/ricardo/.pyenv/versions/3.8.12/bin/python -m pip install --upgrade pip' command.


In [6]:
# Passe seu username e sua chave
# Pesquisar como ler um json sem ter que expor a chave no código
kaggle_config = {
    "username": "dairi97",
    "key": "253fef63306bb7f36fd8d8b398a30b22"
}

# Validando se a biblioteca kaggle realmente esta instalada
os.makedirs(os.path.join(os.path.expanduser('~'), '.kaggle'), exist_ok=True)

# Escrevendo .json file do kaggle
with open(os.path.join(os.path.expanduser('~'), '.kaggle/kaggle.json'), 'w') as file:
    json.dump(kaggle_config, file)

# Setando permissões
os.chmod(os.path.join(os.path.expanduser('~'), '.kaggle/kaggle.json'), 0o600)

In [7]:
def download_kaggle_dataset(dataset):
    subprocess.run(['kaggle', 'datasets', 'download', '-d', dataset])

download_kaggle_dataset('olistbr/brazilian-ecommerce')

 87%|████████▋ | 37.0M/42.6M [00:02<00:00, 24.9MB/s]

100%|██████████| 42.6M/42.6M [00:02<00:00, 17.6MB/s]


In [8]:
import zipfile
import pandas as pd

# Unzipping the dataset
with zipfile.ZipFile('brazilian-ecommerce.zip', 'r') as zip_ref:
    zip_ref.extractall('brazilian_ecommerce')

# Reading a file from the dataset
# Replace 'file_name.csv' with the actual file name you want to read
df = pd.read_csv('brazilian_ecommerce/file_name.csv')
print(df.head())

FileNotFoundError: [Errno 2] No such file or directory: 'brazilian_ecommerce/file_name.csv'